### ISSUE TITLE
About support for .NET Core 1.0

### ISSUE THREAD

**Issue by LonghronShen** [2Toad/Rijndael256#11]
I have done a branch for porting back the project to Visual Studio 2015 and change supported frameworks to .NET Standard 1.3 and .NET Framework 4.5.1.
See any possibility to merge back to the main repo?
This is [my fork](https://github.com/LonghronShen/Rijndael256).

**Comment by JasonPierce** [comment]
Hi @LonghronShen. Please submit a PR, and I'll take a look

**Comment by JasonPierce** [comment]
Closing since the PR build was never fixed
