### ISSUE TITLE
.NET Core 3.1 - Initialization vector 256 bits not supported

### ISSUE THREAD

**Issue by dericferreira** [2Toad/Rijndael256#16]
Hey,

If .NET Core 3.1 still does not support 256 initialization vector why documentation does not reflect that?

Look at this:

//RijndaelManaged
//        Legal min key size = 128
//        Legal max key size = 256
//        Legal min block size = 128
**//        Legal max block size = 256**

Anybody can't get the same result! Why does the documentation is not refleting the truth?

https://docs.microsoft.com/pt-br/dotnet/api/system.security.cryptography.symmetricalgorithm.legalkeysizes?view=netcore-3.1

_Originally posted by @dericferreira in https://github.com/2Toad/Rijndael256/issues/13#issuecomment-635318470_

**Comment by JasonPierce** [comment]
@dericferreira a better place for this type of question would be on StackOverflow or in the .NET Core repo: https://github.com/dotnet/core, since it doesn't apply to this lib, specifically
